version: 2
#creation of our sources, the dataset we used and import from our BigQuery data Wharehouse.
sources:
  - name: raw_data
    schema: raw_data
    tables:
      - name: conso_prod_2013_2023_30min_renamed
        identifier: conso_prod_2013_2023_30min_renamed

      - name: conso_prod_2023_2024_15min_renamed
        identifier: conso_prod_2023_2024_15min_renamed
    
      - name: fc_tc_regionaux_mensuels_renamed
        identifier: fc_tc_regionaux_mensuels_renamed

      - name: prod_enr_region_annuelle_renamed
        identifier: prod_enr_region_annuelle_renamed

      - name: prod_filiere_regionale_mensuelle_renamed
        identifier: prod_filiere_regionale_mensuelle_renamed
      - name: conso_prod__2013_2024_30min
        identifier: conso_prod__2013_2024_30min
#models:
  #- name:
  #  description: 
  #  columns:
      