version: 2

sources:
  - name: raw
    schema: raw_data
    tables:
      - name: prod_regionale_annuelle_enr
        identifier: prod_regionale_annuelle_enr

      - name: eco2mix_regional_alldata
        identifier: eco2mix_regional_alldata

      - name: production_regionale_mensuelle_filiere
        identifier: production_regionale_mensuelle_filiere


        
      