version: 2

sources:
  - name: raw
    schema: raw_data
    tables:
      - name: prod_regionale_annuelle_enr
        identifier: prod_regionale_annuelle_enr

    # Below, created others view from other raw dataset